# version: "3.9"
services:
    redis:
        image: redis:latest
        container_name: rw-redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

    matchmaking-service:
        build: ./matchmaking-service
        container_name: rw-matchmaking-service
        ports:
            - "8081:8081"
        depends_on:
            redis:
                condition: service_healthy
        environment:
            - REDIS_HOST=redis

    gameplay-service:
        build: ./gameplay-service
        container_name: rw-gameplay-service
        ports:
            - "8082:8082"
        depends_on:
            redis:
                condition: service_healthy
        environment:
            - REDIS_HOST=redis

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        restart: always
