# version: "3.9"
services:
    # frontend:
    #     build: ./frontend
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - matchmaking-service
    #         - gameplay-service

    # matchmaking-service:
    #     build: ./matchmaking-service
    #     container_name: rw-matchmaking-service
    #     ports:
    #         - "8081:8081"
    #     depends_on:
    #         - redis

    # gameplay-service:
    #     build: ./gameplay-service
    #     ports:
    #         - "8082:8082"
    #     depends_on:
    #         - redis

    redis:
        image: redis:latest
        container_name: rw-redis
        ports:
            - "6379:6379"
