services:
    - type: redis
      name: rw-redis
      plan: free
      ipAllowList: [] # empty list = allow all internal connections

    - type: web
      name: matchmaking-service
      env: docker
      dockerfilePath: ./matchmaking-service/Dockerfile
      plan: free
      autoDeploy: true
      envVars:
          - key: REDIS_HOST
            fromService:
                name: rw-redis
                property: host
          - key: PORT
            value: 8081

    - type: web
      name: gameplay-service
      env: docker
      dockerfilePath: ./gameplay-service/Dockerfile
      plan: free
      autoDeploy: true
      envVars:
          - key: REDIS_HOST
            fromService:
                name: rw-redis
                property: host
          - key: PORT
            value: 8082

    - type: web
      name: frontend
      env: docker
      dockerfilePath: ./frontend/Dockerfile
      plan: free
      autoDeploy: true
      envVars:
          - key: PORT
            value: 3000
